const judge = [
  { value: 0, label: 'Todos' },
  { value: 2, label: '1º Juzgado de Letras de Arica' },
  { value: 1400, label: '1º Juzgado De Letras de Arica ex 4°' },
  { value: 3, label: '2º Juzgado de Letras de Arica' },
  { value: 1401, label: '2º Juzgado De Letras de Arica ex 4°' },
  { value: 4, label: '3º Juzgado de Letras de Arica' },
  { value: 5, label: '3º Juzgado de Letras de Arica Ex 4º' },
  { value: 6, label: 'Juzgado de Letras y Gar. Pozo Almonte' },
  { value: 9, label: '1º Juzgado de Letras de Iquique' },
  { value: 10, label: '2º Juzgado de Letras de Iquique' },
  { value: 11, label: '3º Juzgado de Letras de Iquique' },
  { value: 13, label: 'Juzgado de Letras Tocopilla' },
  { value: 14, label: 'Juzgado de Letras y Gar.de María Elena' },
  { value: 16, label: '1º Juzgado de Letras de Calama' },
  { value: 17, label: '2º Juzgado de Letras de Calama' },
  { value: 658, label: '3º Juzgado de Letras de Calama' },
  { value: 26, label: 'Juzgado de Letras y Gar. de Taltal' },
  { value: 1041, label: '1º Juzgado de Letras Civil de Antofagasta' },
  { value: 1042, label: '2º Juzgado de Letras Civil de Antofagasta' },
  { value: 1043, label: '3º Juzgado de Letras Civil de Antofagasta' },
  { value: 1044, label: '4 ° Juzgado de Letras Civil de Antofagasta' },
  { value: 1501, label: 'Juzgado de Letras y Garantía Mejillones' },
  { value: 27, label: 'Juzgado de Letras y Gar. de Chañaral' },
  { value: 29, label: 'Juzgado de Letras de Diego de Almagro' },
  { value: 31, label: '1º Juzgado de Letras de Copiapó' },
  { value: 32, label: '2º Juzgado de Letras de Copiapó' },
  { value: 33, label: '3º Juzgado de Letras de Copiapó' },
  { value: 34, label: 'Juzgado de Letras y Gar.de Freirina' },
  { value: 926, label: '4º Juzgado de Letras de Copiapó' },
  { value: 36, label: '1º Juzgado de Letras de Vallenar' },
  { value: 37, label: '2º Juzgado de Letras de Vallenar' },
  { value: 386, label: 'Juzgado de Letras y Gar.de Caldera' },
  { value: 40, label: '1º Juzgado de Letras de la Serena' },
  { value: 41, label: '2º Juzgado de Letras de la Serena' },
  { value: 42, label: '3º Juzgado de Letras de la Serena' },
  { value: 43, label: '1º Juzgado de Letras de Coquimbo' },
  { value: 44, label: '2º Juzgado de Letras de Coquimbo' },
  { value: 45, label: '3º Juzgado de Letras de Coquimbo' },
  { value: 46, label: 'Juzgado de Letras de Vicuña' },
  { value: 47, label: 'Juzgado de letras y garantía de Andacollo' },
  { value: 48, label: '1º Juzgado de Letras de Ovalle' },
  { value: 49, label: '2º Juzgado de Letras de Ovalle' },
  { value: 50, label: '3º Juzgado de Letras de Ovalle' },
  { value: 51, label: 'Juzgado de Letras y Gar.de Combarbalá' },
  { value: 52, label: 'Juzgado de Letras de Illapel' },
  { value: 53, label: 'Juzgado de Letras y Gar. de los Vilos' },
  { value: 56, label: '1º Juzgado Civil de Valparaíso' },
  { value: 55, label: '2º Juzgado Civil de Valparaíso' },
  { value: 54, label: '3º Juzgado Civil de Valparaíso' },
  { value: 59, label: '4º Juzgado Civil de Valparaíso' },
  { value: 60, label: '5º Juzgado Civil de Valparaíso' },
  { value: 57, label: '1º Juzgado Civil de Viña del Mar' },
  { value: 58, label: '2º Juzgado Civil de Viña del Mar' },
  { value: 61, label: '3º Juzgado Civil de Viña del Mar' },
  { value: 83, label: '1º Juzgado de Letras de Quilpue' },
  { value: 84, label: '2º Juzgado de Letras de Quilpue' },
  { value: 85, label: 'Juzgado de Letras de Villa Alemana' },
  { value: 86, label: 'Juzgado de Letras de Casablanca' },
  { value: 87, label: 'Juzgado de Letras de La Ligua' },
  { value: 88, label: 'Juzgado de Letras y Gar. de Petorca' },
  { value: 89, label: '1º Juzgado de Letras de Los Andes' },
  { value: 90, label: '2º Juzgado de Letras de Los Andes' },
  { value: 92, label: '1º Juzgado de Letras de San Felipe' },
  { value: 93, label: '1º Juzgado de Letras de San Felipe Ex 2º' },
  { value: 94, label: 'Juzgado de Letras y Gar.de Putaendo' },
  { value: 96, label: '1º Juzgado de Letras de Quillota' },
  { value: 97, label: '2º Juzgado de Letras de Quillota' },
  { value: 98, label: 'Juzgado de Letras de La Calera' },
  { value: 99, label: 'Juzgado de Letras de Limache' },
  { value: 101, label: '1º Juzgado de Letras de San Antonio' },
  { value: 102, label: '2º Juzgado de Letras de San Antonio' },
  { value: 103, label: 'Juzgado de Letras y Gar. de Isla de Pascua' },
  { value: 660, label: 'Juzgado de Letras y Gar.de Quintero' },
  { value: 110, label: '1º Juzgado Civil de Rancagua' },
  { value: 969, label: '2º Juzgado Civil de Rancagua' },
  { value: 111, label: '1º Juzgado de Letras de Rengo' },
  { value: 113, label: 'Juzgado de Letras de San Vicente de Tagua Tagua' },
  { value: 114, label: '1º Juzgado de Letras y Gar.de Peumo' },
  { value: 115, label: '1º Juzgado de Letras de San Fernando' },
  { value: 116, label: '2º Juzgado de Letras de San Fernando' },
  { value: 117, label: '1º Juzgado de Letras de Santa Cruz' },
  { value: 118, label: '1º Juzgado De Letras De Santa Cruz Ex 2°' },
  { value: 119, label: 'Juzgado de Letras y Gar.de Pichilemu' },
  { value: 1150, label: 'Juzgado de Letras y Gar.de Litueche' },
  { value: 1151, label: 'Juzgado de Letras y Gar.de Peralillo' },
  { value: 122, label: '1º Juzgado de Letras de Talca' },
  { value: 123, label: '2º Juzgado de Letras de Talca' },
  { value: 124, label: '3º Juzgado de Letras de Talca' },
  { value: 125, label: '4º Juzgado de Letras de Talca' },
  { value: 126, label: 'Juzgado de Letras de Constitución' },
  { value: 127, label: 'Juzgado De Letras Y Gar. de Curepto' },
  { value: 129, label: '1º Juzgado de Letras de Curicó' },
  { value: 130, label: '2º Juzgado de Letras de Curicó' },
  { value: 131, label: '2º Juzgado de Letras de Curicó Ex 3°' },
  { value: 132, label: 'Juzgado De Letras Y Gar. de Licantén' },
  { value: 133, label: 'Juzgado de Letras de Molina' },
  { value: 135, label: '1º Juzgado de Letras de Linares' },
  { value: 136, label: '2º Juzgado de Letras de Linares' },
  { value: 138, label: 'Juzgado de Letras de San Javier' },
  { value: 139, label: 'Juzgado de Letras de Cauquenes' },
  { value: 140, label: 'Juzgado de Letras y Gar. de Chanco' },
  { value: 141, label: 'Juzgado de Letras de Parral' },
  { value: 145, label: '1º Juzgado Civil de Chillán' },
  { value: 146, label: '2º Juzgado Civil de Chillán' },
  { value: 147, label: '1º Juzgado de Letras de San Carlos' },
  { value: 149, label: 'Juzgado de Letras de Yungay' },
  { value: 150, label: 'Juzgado de Letras y Gar. de Bulnes' },
  { value: 151, label: 'Juzgado de Letras y Gar.de Coelemu' },
  { value: 152, label: 'Juzgado de Letras y Gar.de Quirihue' },
  { value: 154, label: '1º Juzgado de Letras de Los Angeles' },
  { value: 155, label: '2º Juzgado de Letras de Los Angeles' },
  { value: 156, label: '2° Juzgado de Letras de Los Angeles ex 3°' },
  { value: 157, label: 'Juzgado de Letras y Gar. de Mulchen' },
  { value: 158, label: 'Juzgado de Letras y Gar.de Nacimiento' },
  { value: 159, label: 'Juzgado de Letras y Gar.de Laja' },
  { value: 160, label: 'Juzgado de Letras y Gar.de Yumbel' },
  { value: 161, label: '1º Juzgado Civil de Concepción' },
  { value: 162, label: '2º Juzgado Civil de Concepción' },
  { value: 163, label: '3º Juzgado Civil de Concepción' },
  { value: 179, label: '1º Juzgado Civil de Talcahuano' },
  { value: 180, label: '2º Juzgado Civil de Talcahuano' },
  { value: 187, label: 'Juzgado de Letras de Tomé' },
  { value: 188, label: 'Juzgado de Letras y Gar.de Florida' },
  { value: 189, label: 'Juzgado de Letras y Gar.de Santa Juana' },
  { value: 190, label: 'Juzgado de Letras y Gar. de Lota' },
  { value: 191, label: '1º Juzgado de Letras de Coronel' },
  { value: 192, label: '2º Juzgado de Letras de Coronel' },
  { value: 193, label: 'Juzgado de Letras y Gar.de Lebu' },
  { value: 194, label: 'Juzgado de Letras de Arauco' },
  { value: 195, label: 'Juzgado de Letras y Gar.de Curanilahue' },
  { value: 196, label: 'Juzgado de Letras de Cañete' },
  { value: 385, label: 'Juzgado de Letras y Gar. Santa Bárbara' },
  { value: 1152, label: 'Juzgado de Letras y Gar.de Cabrero' },
  { value: 197, label: '1º Juzgado Civil de Temuco' },
  { value: 198, label: '2º Juzgado Civil de Temuco' },
  { value: 204, label: 'Juzgado de Letras de Angol' },
  { value: 206, label: 'Juzgado de Letras y Gar.de Collipulli' },
  { value: 207, label: 'Juzgado de Letras y Gar.de Traiguén' },
  { value: 208, label: 'Juzgado de Letras de Victoria' },
  { value: 209, label: 'Juzgado de Letras y Gar.de Curacautin' },
  { value: 210, label: 'Juzgado de Letras Loncoche' },
  { value: 211, label: 'Juzgado de Letras de Pitrufquen' },
  { value: 212, label: 'Juzgado de Letras de Villarrica' },
  { value: 213, label: 'Juzgado de Letras de Nueva Imperial' },
  { value: 214, label: 'Juzgado de Letras y Gar.de Pucón' },
  { value: 215, label: 'Juzgado de Letras de Lautaro' },
  { value: 216, label: 'Juzgado de Letras y Gar.de Carahue' },
  { value: 406, label: '3º Juzgado Civil de Temuco' },
  { value: 946, label: 'Juzgado de Letras y Gar.de Tolten' },
  { value: 947, label: 'Juzgado de Letras y Gar.de Puren' },
  { value: 220, label: '1º Juzgado Civil de Valdivia' },
  { value: 221, label: '2º Juzgado Civil de Valdivia' },
  { value: 222, label: 'Juzgado de Letras de Mariquina' },
  { value: 223, label: 'Juzgado de Letras y Gar.de Paillaco' },
  { value: 224, label: 'Juzgado de Letras Los Lagos' },
  { value: 225, label: 'Juzgado de Letras y Gar. de Panguipulli' },
  { value: 226, label: 'Juzgado de Letras y Gar.de la Unión' },
  { value: 227, label: 'Juzgado de Letras y Gar.de Río Bueno' },
  { value: 229, label: '1º Juzgado de Letras de Osorno' },
  { value: 230, label: '2º Juzgado de Letras de Osorno' },
  { value: 233, label: 'Juzgado de Letras de Rio Negro' },
  { value: 237, label: '1º Juzgado Civil de Puerto Montt' },
  { value: 1012, label: '2º Juzgado Civil de Puerto Montt' },
  { value: 238, label: 'Juzgado de Letras de Puerto Varas' },
  { value: 240, label: 'Juzgado de Letras y Gar.de Calbuco' },
  { value: 241, label: 'Juzgado de Letras y Gar. de Maullin' },
  { value: 242, label: 'Juzgado de Letras de Castro' },
  { value: 243, label: 'Juzgado de Letras de Ancud' },
  { value: 244, label: 'Juzgado de Letras y Garantía de Achao' },
  { value: 245, label: 'Juzgado de Letras y Gar. de Chaitén' },
  { value: 659, label: 'Juzgado de Letras y Gar. de Los Muermos' },
  { value: 662, label: 'Juzgado de Letras y Gar. de Quellón' },
  { value: 1013, label: 'Juzgado de Letras y Gar. de Hualaihue' },
  { value: 246, label: '1º Juzgado de Letras de Coyhaique' },
  { value: 247, label: '1º Juzgado de Letras de Coyhaique Ex 2º' },
  { value: 248, label: 'Juzgado de Letras y Gar.de pto.Aysen' },
  { value: 249, label: 'Juzgado de Letras y Gar.de Chile Chico' },
  { value: 250, label: 'Juzgado de Letras y Gar.de Cochrane' },
  { value: 996, label: 'Juzgado de Letras y Gar.de Puerto Cisnes' },
  { value: 253, label: '1º Juzgado de Letras de Punta Arenas' },
  { value: 254, label: '2º Juzgado de Letras de Punta Arenas' },
  { value: 255, label: '3º Juzgado de Letras de Punta Arenas' },
  { value: 257, label: 'Juzgado de Letras y Gar. de Puerto Natales' },
  { value: 258, label: 'Juzgado de Letras y Gar.de Porvenir' },
  { value: 1502, label: 'Juzgado de Letras y Garantía de Cabo de Hornos' },
  { value: 259, label: '1º Juzgado Civil de Santiago' },
  { value: 260, label: '2º Juzgado Civil de Santiago' },
  { value: 261, label: '3º Juzgado Civil de Santiago' },
  { value: 262, label: '4º Juzgado Civil de Santiago' },
  { value: 263, label: '5º Juzgado Civil de Santiago' },
  { value: 264, label: '6º Juzgado Civil de Santiago' },
  { value: 265, label: '7º Juzgado Civil de Santiago' },
  { value: 266, label: '8º Juzgado Civil de Santiago' },
  { value: 267, label: '9º Juzgado Civil de Santiago' },
  { value: 268, label: '10º Juzgado Civil de Santiago' },
  { value: 269, label: '11º Juzgado Civil de Santiago' },
  { value: 270, label: '12º Juzgado Civil de Santiago' },
  { value: 271, label: '13º Juzgado Civil de Santiago' },
  { value: 272, label: '14º Juzgado Civil de Santiago' },
  { value: 273, label: '15º Juzgado Civil de Santiago' },
  { value: 274, label: '16º Juzgado Civil de Santiago' },
  { value: 275, label: '17º Juzgado Civil de Santiago' },
  { value: 276, label: '18º Juzgado Civil de Santiago' },
  { value: 277, label: '19º Juzgado Civil de Santiago' },
  { value: 278, label: '20º Juzgado Civil de Santiago' },
  { value: 279, label: '21º Juzgado Civil de Santiago' },
  { value: 280, label: '22º Juzgado Civil de Santiago' },
  { value: 281, label: '23º Juzgado Civil de Santiago' },
  { value: 282, label: '24º Juzgado Civil de Santiago' },
  { value: 283, label: '25º Juzgado Civil de Santiago' },
  { value: 284, label: '26º Juzgado Civil de Santiago' },
  { value: 285, label: '27º Juzgado Civil de Santiago' },
  { value: 286, label: '28º Juzgado Civil de Santiago' },
  { value: 287, label: '29º Juzgado Civil de Santiago' },
  { value: 288, label: '30º Juzgado Civil de Santiago' },
  { value: 387, label: 'Juzgado de Letras de Colina' },
  { value: 343, label: '1º Juzgado Civil de San Miguel' },
  { value: 344, label: '2º Juzgado Civil de San Miguel' },
  { value: 345, label: '3º Juzgado Civil de San Miguel' },
  { value: 390, label: '4º Juzgado Civil de San Miguel' },
  { value: 364, label: '1º Juzgado Civil de Puente Alto' },
  { value: 373, label: '1º Juzgado De Letras De Talagante' },
  { value: 374, label: '2º Juzgado De Letras De Talagante' },
  { value: 375, label: '1º Juzgado de Letras de Melipilla' },
  { value: 377, label: '1º Juzgado de Letras de Buin' },
  { value: 378, label: '2º Juzgado de Letras de Buin' },
  { value: 388, label: 'Juzgado de Letras de Peñaflor' },
  { value: 400, label: '1º Juzgado de Letras de San Bernardo' },
  { value: 1402, label: '1º Juzgado de Letras de San Bernardo Ex 3°' },
  { value: 401, label: '2º Juzgado de Letras de San Bernardo' },
  { value: 1403, label: '2º Juzgado de Letras de San Bernardo Ex 3°' }
]

// Función mejorada para obtener ID desde nombre (con soporte para múltiples formatos)
const courtIdByName = (name) => {
  // Primero intentar búsqueda directa
  let res = judge.filter(i => i.label === name)
  if (res.length > 0) return res[0].value
  
  // Si no, intentar búsqueda parcial (para casos como "15º Juzgado Civil de Santiago" vs "15º Juzgado Civil de Santiago")
  res = judge.filter(i => i.label.toLowerCase() === name.toLowerCase())
  if (res.length > 0) return res[0].value
  
  // Si aún no, intentar buscar por número de juzgado (ej: "15º")
  const match = name.match(/(\d+)[º°]/)
  if (match) {
    const number = parseInt(match[1])
    res = judge.filter(i => i.label.includes(`${number}º`))
    if (res.length > 0) return res[0].value
  }
  
  console.warn(`⚠️ No se encontró ID para el tribunal: ${name}`)
  return null
}

module.exports = {
  courtNameById: id => {
    const res = judge.filter(i => i.value === parseInt(id))
    return res[0]?.label || ''
  },
  courtIdByName: courtIdByName  // ← Función mejorada
}